name: CI Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-ansi --no-root

    - name: Run flake8 linter
      run: |
        poetry run flake8 .

    - name: Run tests
      run: |
        poetry run python -m pytest tests/test_router.py -v